# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/foyerdb
spring.data.mongodb.database=foyerdb

# Server Configuration
server.port=8081

# DevTools / restart behavior
spring.devtools.restart.enabled=false
spring.devtools.add-properties=false
spring.devtools.livereload.enabled=false